### ISSUE TITLE
gingerbread houses

### ISSUE THREAD

**Issue by bagool185** [JesseBoogaard/shrekraft#1]
add gingerbread houses

**Comment by JesseBoogaard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gingerbread houses](https://trello.com/c/iQOxyCVD/69-gingerbread-houses)

**Comment by JesseBoogaard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gingerbread house](https://trello.com/c/oy1f8zXc/73-gingerbread-house)

**Comment by bagool185** [comment]
rip

**Comment by JesseBoogaard** [comment]
@bagool185 Rip indeed
